version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/config.development.articles-library.list
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r17BDyxd3rJmF9NIlGZP
      POSTGRES_DB: library