version: '3'
services:
  app_test:
    build:
      context: . 
      dockerfile: Dockerfile.test
    env_file:
      - ./config/config.development.articles-library.list
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r17BDyxd3rJmF9NIlGZP
      POSTGRES_DB: library